version: 0.2
   
phases:
  pre_build:
    commands:
      - echo "login into ecr"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
       
    
  build:
    commands:
      - echo "Building an docker image"      
      - docker build -t testdfef:latest .
      - echo "tag an image"
      - docker tag testdfef:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/testdfef:latest
    
  post_build:
    commands:
      - echo "image has been build"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/testdfef:latest
