version: 0.2
   
phases:
  pre_build:
    commands:
      - echo "login into ecr"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 467036924094.dkr.ecr.us-east-2.amazonaws.com
      - echo "installing docker"
      - apt-get update
      - apt-get install ca-certificates curl gnupg
      - sudo install -m 0755 -d /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      - sudo chmod a+r /etc/apt/keyrings/docker.gpg
      - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - sudo apt-get update
      - sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin 
      - echo "docker installed"
      - service docker start
  
    
  build:
    commands:
      - echo "Building an docker image"      
      - docker build -t testdfef .
      - echo "tag an image"
      - docker tag testdfef:latest 467036924094.dkr.ecr.us-east-2.amazonaws.com/testdfef:latest
    
  post_build:
    commands:
      - echo "image has been build"
      - docker push 467036924094.dkr.ecr.us-east-2.amazonaws.com/testdfef:latest
